# Generated by Django 3.0.14 on 2022-07-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_auto_20220709_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room_name',
            new_name='roomname',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_name',
            new_name='roomname',
        ),
    ]
