# Generated by Django 3.0.14 on 2022-07-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_auto_20220709_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='admin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
