# Generated by Django 3.0.14 on 2022-07-10 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_room_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='admin',
            new_name='adminname',
        ),
        migrations.RemoveField(
            model_name='room',
            name='password',
        ),
    ]
