# Generated by Django 3.0.14 on 2022-07-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_auto_20220710_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='block_user',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
