# Generated by Django 3.0.14 on 2022-07-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0008_room_block_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='block_user',
        ),
        migrations.AddField(
            model_name='room',
            name='blockuser',
            field=models.TextField(blank=True),
        ),
    ]
