# Generated by Django 3.0.14 on 2022-07-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_auto_20220713_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='blockuser',
            field=models.CharField(blank=True, max_length=10000000),
        ),
    ]
